---
# tasks file for roles/database
- name: Install and Launch database
  docker_container:
    name: my-db
    image: tploix/tp-devops-database:latest
    env:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    networks:
      - name: my-network
  tags: database
