---
# tasks file for roles/database
- name: Install and Launch database
  docker_container:
    name: my_database
    image: tploix/tp-devops-database:latest
    env:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pwd
    ports:
      - "5432:5432"
    networks:
      - name: network_app
  tags: database
