---
# tasks file for roles/front
- name: Launch front container
  docker_container:
    name: front
    image: tploix/tp-devops-http-server:latest
    state: started
    ports:
      - "80:80"
    networks:
      - name: my-network
