---
# tasks file for roles/front
- name: Launch front container
  docker_container:
    image: tploix/tp-devops-front-server:latest
    state: started
    ports:
      - "13:13"
    networks:
      - name: my-network
