---
# tasks file for roles/proxy
- name: Launch front container
  docker_container:
    name: httpd
    image: tploix/tp-devops-proxy-server:latest
    state: started
    ports:
      - "80:80"

  tags: proxy


