---
# tasks file for roles/proxy
- name: Launch front container
  docker_container:
    name: httpd
    image: tploix/tp-devops-http-server:latest
    state: started
    ports:
      - "80:80"
    networks:
      - name: my-network

  tags: proxy


