---
# tasks file for roles/proxy
- name: Launch Proxy container
  docker_container:
    name: httpd
    image: tploix/tp-devops-proxy-server:latest
    state: started
    networks:
      - name: my-network
  tags: proxy


